name: 'Testing OpenVPN 3 Action'

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: dbritto-dev/openvpn3-action@v1
        with:
          vpn-client-config: ${{ secrets.VPN_CLIENT_CONFIG }}
          vpn-autoload-config: ${{ secrets.VPN_AUTOLOAD_CONFIG }}
          script: |
            openvpn3 sessions-list
